### ISSUE TITLE
un-hardwire available scheduler systems everywhere!

### ISSUE THREAD

**Issue by sfranky** [qtop/qtop#101]

**Comment by lookfwd** [comment]
In progress (?)

**Comment by fgeorgatos** [comment]
this has been done?

**Comment by sfranky** [comment]
````
def scheduler_factory(scheduler, scheduler_output_filenames, config):
    if scheduler == "pbs":
        return PBSBatchSystem(scheduler_output_filenames, config)
    elif scheduler == "oar":
        return OARBatchSystem(scheduler_output_filenames, config)
    elif scheduler == "sge":
        return SGEBatchSystem(scheduler_output_filenames, config)
````
@lookfwd any ideas on how to un-hardwire this?? inclusion of the scheduler choices+ their CLASS on the config yaml file? seems a bit weird to me!

**Comment by lookfwd** [comment]
hmmm

**Comment by lookfwd** [comment]
We have a try-except party here:

https://github.com/qtop/qtop/blob/5607bcf6ad01f06a981fdf5980dc30c539887a3c/qtop.py#L1218

I think this can be compacted like this:

```
def decide_batch_system(cmdline_switch, env_var, config_file_batch_option):
    """
    Qtop first checks in cmdline switches, environmental variables and the config files, in this order,
    for the scheduler type. If it's not indicated and "auto" is, it will attempt to guess the scheduler type
    from the scheduler shell commands available in the linux system.
    """
    if cmdline_switch and cmdline_switch.lower() not in ['sge', 'oar', 'pbs', 'auto']:
        logging.critical("Selected scheduler system not supported. Available choices are 'PBS', 'SGE', 'OAR'.")
        logging.critical("For help, try ./qtop.py --help")
        logging.critical("Log file created in %s" % expandvars(QTOP_LOGFILE))
        raise InvalidScheduler
    for scheduler in (cmdline_switch, env_var, config_file_batch_option):
        try:
            scheduler = scheduler.lower()
        except AttributeError:
            # ??? What's the value of scheduler in this case?
			# Pass feels liek a but... likely just a check on 
			# type of scheduler being string or something, but
			# not within a try-except? What will be the value
			# if we hit this pass?
            pass

        if scheduler == 'auto':
            scheduler = auto_get_avail_batch_system()
            logging.debug('Selected scheduler is %s' % scheduler)
            return scheduler
        elif scheduler in config['schedulers']:
            logging.info('User-selected scheduler: %s' % scheduler)
            return scheduler
        elif scheduler and scheduler not in config['schedulers']:  # a scheduler that does not exist is inputted
			break
				
	raise NoSchedulerFound
```

**Comment by lookfwd** [comment]
We shouldn't be using those anymore, right? Calls for each subsystem get now done only via appropriate classes e.g. `PBSBatchSystem`?
```
from plugins.pbs import *
from plugins.oar import *
from plugins.sge import *
```

**Comment by lookfwd** [comment]
`class StatExtractor(object):`

This interface isn't used yet, right?

**Comment by sfranky** [comment]
````
def decide_batch_system(cmdline_switch, env_var, config_file_batch_option):
    if cmdline_switch and cmdline_switch.lower() not in ['sge', 'oar', 'pbs', 'auto']:
        logging.critical("Selected scheduler system not supported. Available choices are 'PBS', 'SGE', 'OAR'.")
        logging.critical("For help, try ./qtop.py --help")
        logging.critical("Log file created in %s" % expandvars(QTOP_LOGFILE))
        raise InvalidScheduler
    for scheduler in (cmdline_switch, env_var, config_file_batch_option):
        try:
            scheduler = scheduler.lower()
        except AttributeError:
            # ??? What's the value of scheduler in this case?
            # Pass feels liek a but... likely just a check on 
            # type of scheduler being string or something, but
            # not within a try-except? What will be the value
            # if we hit this pass?
            pass
        ......
    
    raise NoSchedulerFound
````
If None of the three options are provided by the user (cmdline switch, envvar, configfile option), scheduler's value is well... None! 
So, no .lower() method, and thus I let it pass so that NoSchedulerFound is raised in the end!

**Comment by lookfwd** [comment]
More on the low level mechanics in PR #139

**Comment by lookfwd** [comment]
> Hmmm, I see now, you mean I should have raised it early so it wouldn't have to pass through that unnecessary if-elif-elif ?

Yes, I believe that something like: `assert type(x) == str` should be ok... and then assume that it has `.lower()`. After all as far as I can tell `scheduler` being anything other than string is a software error... In which cases could it be non-string?

**Comment by sfranky** [comment]
If the user runs qtop.py without a -b <scheduler> switch, and there's nothing in the config file or in an environmental variable, scheduler isn't assigned to anything. Why consider it a software error?

**Comment by sfranky** [comment]
> We shouldn't be using those anymore, right? Calls for each subsystem get now done only via appropriate classes e.g. PBSBatchSystem?

> from plugins.pbs import *
> from plugins.oar import *
> from plugins.sge import *

Alas, these classes *exist* in those modules, hence the problem. I needed to find a way to import just the appropriate module each time

**Comment by sfranky** [comment]
>class StatExtractor(object):

>This interface isn't used yet, right?

Why not? the derived classes sure are!
e.g.
````
class PBSBatchSystem(GenericBatchSystem):
    def __init__(self, scheduler_output_filenames, config):
        self.pbsnodes_file = scheduler_output_filenames.get('pbsnodes_file')
        self.qstat_file = scheduler_output_filenames.get('qstat_file')
        self.qstatq_file = scheduler_output_filenames.get('qstatq_file')

        self.config = config
        self.qstat_maker = PBSStatExtractor(self.config)
````

**Comment by sfranky** [comment]
> something like: assert type(x) == str should be ok.

An assertion on the type of scheduler would fail in the iterations of the for loop that don't contain anything. Am I missing something obvious here?

>     for scheduler in (cmdline_switch, env_var, config_file_batch_option):
            ....

**Comment by lookfwd** [comment]
> Alas, these classes exist in those modules, hence the problem. I needed to find a way to import just the appropriate module each time

I think that the way I have in #139 should work!

> Why not? the derived classes sure are!

I think that's true on Develop but not master... not sure - might have overlooked. The only thing that worries me with those is that they are a bit "very top level".

Specially when 

`from plugins.oar import *`

used to happen... they used to be imported directly to `qtop.py` which wasn't using them per se. Not sure what the best way is there... Maybe merge the two classes or... do nothing. They are ok... just a bit confusing. :)

> If the user runs qtop.py without a -b [scheduler] switch, and there's nothing in the config file or in an environmental variable, variable scheduler isn't assigned to anything. Why consider it a software error?

In that case - I guess - you get None? If that's the case, then handle None as a case and let's not make it a big deal (try-catch) :D Hehehe. What I mean... is that there isn't a case that there's e.g. an int or a float or a "WhateverClass" there. If it's either a string or None... then those are two truly ok cases to handle. If we had an int suddenly, it would be software error.

**Comment by lookfwd** [comment]
> An assertion on the type of scheduler would fail in the iterations of the for loop that don't contain anything. Am I missing something obvious here?

No no... I'm missing. Would then something like:

````
If scheduler is None:
    continue
... = scheduler.lower()
...
```

solution work?

**Comment by sfranky** [comment]
Yes I think this is optimal !

**Comment by lookfwd** [comment]
Awesome :)

**Comment by sfranky** [comment]
Awesome work...!!! thanks for that and the PR !! I'm drooling over it !!

**Comment by lookfwd** [comment]
And I think that it would be nice - by default - if it doesn't find a system ... to revert back to a "demo" implementation with a guidance about what qtop is and how it works.

... although this might not be very UNIX-y behaviour :)

**Comment by sfranky** [comment]
[takes southern US-state accent:]
"That ain't how we dooin things 'roun heere"

But, seriously now, I think I like it!!

**Comment by sfranky** [comment]
hardwired mentions of schedulers removed in PR https://github.com/qtop/qtop/pull/157

**Comment by sfranky** [comment]
included in develop branch
