### ISSUE TITLE
Consider refactoring towards a library + front ends architecture

### ISSUE THREAD

**Issue by lookfwd** [qtop/qtop#106]
I feel qtop might be able to be refactored to a set of modules:

A core library of data sources (oar, pbs, sge) + a standard core data model.

Then we have a separate piece of code that is the View-Controler and by default is the console code that already exists. It could support though other interfaces like web.

<img width="871" alt="my ideas - 25" src="https://cloud.githubusercontent.com/assets/789359/12084352/ea595648-b2ba-11e5-879c-113cfe73c953.png">

**Comment by fgeorgatos** [comment]
+1 

the concept of separating view from calculating calculating code has been ever present;
in fact, the biggest pile of issues, under [VIS] tag, would benefit from this one way or another

**Comment by fgeorgatos** [comment]
this is certainly not in its final form, but if you'd agree, I'd close this issue now that viewport is there.
my guess is that it can be generalised further, however not at this phase of progress.
Closing, but reopen if you have specific TODOs!
