### ISSUE TITLE
Silent failures no good for anybody! example: ./qtop/qtop.py -FTgw -o fill_with_user_firstletter=true

### ISSUE THREAD

**Issue by fgeorgatos** [qtop/qtop#119]
this seems to require capitalization of True in a very particular way:

```
[fgeorgatos@ukhx-prd-glhn01 ~]$ ./qtop/qtop.py -FTgw -o fill_with_user_firstletter=true
[fgeorgatos@ukhx-prd-glhn01 ~]$
```

I can see 3 potential issues:
* `true` keyword should really be case insensitive;  `ON`, `oFF`, `yEs`, `nO` should be functional too!
* qtop should never return so much empty output - reference to logfile totally required here
* exception handling should fail softly, ie. this could be a warning as opposed to hard-fail? (not sure)

**Comment by lookfwd** [comment]
> reference to logfile totally required here

+1 ... The whole idea os stderr >> logfie is somewhat insane. That's what stderr is for. :)

Publicly printing exceptions is fine! There shouldn't be that many and when they are they are helping people to post issues and debug. It's not a bad thing to print stacktrace

**Comment by fgeorgatos** [comment]
a brief stacktrace could be OK; we had met situations in the beginning 
where the output was a bit too long and that's why we ended up here;
Good subject to discuss at FOSDEM'16; when are you flying? ;-)

**Comment by lookfwd** [comment]
Train from Kings-X ;) hahaha Next Friday

**Comment by sfranky** [comment]
FIXED!
