### ISSUE TITLE
'Overspill' of slots (more slots than CPU cores) visualization

### ISSUE THREAD

**Issue by georg-rath** [qtop/qtop#120]
Attached a sample output from our dirty script.
![screenshot from 2016-01-27 14 52 22](https://cloud.githubusercontent.com/assets/6113325/12615402/c01eaccc-c505-11e5-8e31-797738f713a0.png)

Also might be of interest: http://slides.com/georg-rath/hpc-round-table-i#/6/2

Best regards,
Georg

**Comment by sfranky** [comment]
this is implemented in an early form, although there is no column to separate the normal from the overspills

**Comment by fgeorgatos** [comment]
I'm with the impression that this has been implemented? 
adding it for review in next batch of activity

**Comment by sfranky** [comment]
yes, it's done
