### ISSUE TITLE
queue info enhancement

### ISSUE THREAD

**Issue by sfranky** [qtop/qtop#136]
queue info per node should either be displayable with the fullnames of the queues involved, OR a legend nearby should explain which queue each letter represents.
The case of multiple queues beginning with the same letter is tricky, though (e.g. grid400, grid500, grid500M). Color coding could be considered.

**Comment by sfranky** [comment]
solved this through both color-coding queues AND showing jobs colored according to their queue!!

**Comment by fgeorgatos** [comment]
close this after merging?!
