### ISSUE TITLE
allow node sorting through cmdline args

### ISSUE THREAD

**Issue by sfranky** [qtop/qtop#151]
Node sorting should be selected through cmdline arguments, not just through the yaml config file

**Comment by sfranky** [comment]
or maybe in interactive mode (--watch), a keypress could cycle through existing sorting setups, 
or prioritize different sorting statements

**Comment by fgeorgatos** [comment]
btw. filtering which was just merged is essentially a step in this direction; 
can we have multiple preselected sorting methods?!

**Comment by sfranky** [comment]
Sorting is now done *live*, which is better than through cmdline arguments ;)
