### ISSUE TITLE
SGE Job states

### ISSUE THREAD

**Issue by m0zes** [qtop/qtop#155]
There are a few Job states for sge that are missing.

A couple that I found in the first 2 minutes: Rs, Rq, Rt, and Rr. They are combination stated indicating that this is at least the second run of the job, (R)e+(s)uspended, (R)e+(q)ueued, (R)e+(t)ransferring, (R)e+(r)unning

**Comment by fgeorgatos** [comment]
Hi Adam,

cases like that should be an easy fix, see this PR:
https://github.com/qtop/qtop/pull/156/files
Feel free to add more to that, either locally to your systems or, by
issuing a PR.

enjoy, F.


On 26 February 2016 at 16:16, Adam Tygart <notifications@github.com> wrote:

> There are a few Job states for sge that are missing.
>
> A couple that I found in the first 2 minutes: Rs, Rq, Rt, and Rr. They are
> combination stated indicating that this is at least the second run of the
> job, (R)e+(s)uspended, (R)e+(q)ueued, (R)e+(t)ransferring, (R)e+(r)unning
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/qtop/qtop/issues/155>.
>



-- 


echo "sysadmin know better bash than english"|sed s/min/mins/ \
  | sed 's/better bash/bash better/' # signal detected in a CERN forum

**Comment by sfranky** [comment]
Addressed in latest [PR](https://github.com/qtop/qtop/pull/159).

**Comment by fgeorgatos** [comment]
develop has the fix now

On 27 February 2016 at 02:24, Sotiris Fragkiskos <notifications@github.com>
wrote:

> Addressed in latest PR <https://github.com/qtop/qtop/pull/159>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/qtop/qtop/issues/155#issuecomment-189546686>.
>



-- 


echo "sysadmin know better bash than english"|sed s/min/mins/ \
  | sed 's/better bash/bash better/' # signal detected in a CERN forum

**Comment by fgeorgatos** [comment]
I have to admit that the current approach of qtop.py isn't very optimal:
SGE states combinations need to be handled separately, and even exact order is important (yikes).
A more generic approach might be to pre-sort the states and act upon that.
In absence of a strong counter-example, we may let it pass for now, but please take a note on this.
