### ISSUE TITLE
Crash (something wrong with your sorting lambda)

### ISSUE THREAD

**Issue by mightybigcar** [qtop/qtop#158]
On a fresh clone, I get the following crash:
```
[cheiny@bora qtop]$ ./qtop.py -a
CRITICAL - There's (probably) something wrong in your sorting lambda in qtopconf.yaml.
ERROR - Uncaught exception
Traceback (most recent call last):
  File "./qtop.py", line 1798, in <module>
    cluster = calculate_cluster(worker_nodes, cluster)
  File "./qtop.py", line 173, in calculate_cluster
    options.REMAP)
  File "./qtop.py", line 911, in map_worker_nodes_to_wn_dict
    sort_worker_nodes(worker_nodes)
  File "./qtop.py", line 788, in sort_worker_nodes
    batch_nodes.sort(key=eval(config['sorting']['user_sort']), reverse=config['sorting']['reverse'])
  File "<string>", line 5, in <lambda>
ValueError: invalid literal for int() with base 10: ''
[cheiny@bora qtop]$
```

We're running OGS 2011.11.p1 on Fedora 20.  Node names are definitely not a pure arithmetic sequence - they're named after beers (for example: lager, porter, marzen) or cars (for example: bora, jaguar).

Let me know if there's any other information I can provide.

**Comment by sfranky** [comment]
could you try with no sorting?
either by:
a) replacing the whole sort: block in qtopconf.yaml (https://gist.github.com/sfranky/69f7fe804ca6b05011ac) with https://gist.github.com/sfranky/6162fe19179bff7236c3
or
b) creating ~/.local/qtop/qtopconf.yaml with just the same [gist](https://gist.github.com/sfranky/6162fe19179bff7236c3)

**Comment by sfranky** [comment]
btw you can view node names with the -F switch

**Comment by mightybigcar** [comment]
> could you try with no sorting?

Still barfs, but with a different stack trace.

```
[cheiny@bora qtop]$ ./qtop.py -a
ERROR - Uncaught exception
Traceback (most recent call last):
  File "./qtop.py", line 1772, in <module>
    config = load_yaml_config()
  File "./qtop.py", line 689, in load_yaml_config
    config = read_yaml_natively(os.path.join(realpath(QTOPPATH), QTOPCONF_YAML))
  File "/mnt/venom/cheiny/tools/qtop/yaml_parser.py", line 109, in read_yaml_natively
    block, line = read_yaml_config_block(line, fin, get_lines)
  File "/mnt/venom/cheiny/tools/qtop/yaml_parser.py", line 141, in read_yaml_config_block
    or (line[0] == 1 and (key_value.keys()[0] == '-'))\
UnboundLocalError: local variable 'key_value' referenced before assignment
[cheiny@bora qtop]$
```

**Comment by mightybigcar** [comment]
This patch seems to get a bit further: https://gist.github.com/mightybigcar/34cd60528c20ddb29d0e

But it still crashes
```
[cheiny@bora qtop]$ ./qtop.py -a -F
ERROR - Uncaught exception
Traceback (most recent call last):
  File "./qtop.py", line 1772, in <module>
    config = load_yaml_config()
  File "./qtop.py", line 756, in load_yaml_config
    config['sorting']['reverse'] = eval(config['sorting']['reverse'])  # TODO config should not be writeable!!
KeyError: 'reverse'
[cheiny@bora qtop]$
```

**Comment by sfranky** [comment]
Hi, could you try entering gitter? I'm not sure if it requires a login, but
it's worth trying anyway!
https://gitter.im/qtop?utm_source=share-link&utm_medium=link&utm_campaign=share-link

The parser is a bit strict yet, you have to respect the empty line before
the key reverse!

**Comment by sfranky** [comment]
for example, does this work?
```
sorting:
  user_sort: |
      lambda d: (
      # 0  # no sorting, comment following lines until (excluding) closing parenthesis
      d['np'], # sort by number of cores
      ord(d['domainname'][0]), # sort by first letter
      len(d['domainname'].split('.', 1)[0].split('-')[0]),  # by name?
      #int(d['domainname'].split('.', 1)[0].split('-')[1]), 
      #int(re.sub(r'[A-Za-z_-]+', '', d['domainname'].split('.', 1)[0].split('-')[0]) or -1),  # by number
      int(re.sub(r'[A-Za-z _.-]+', '', d['domainname']) or "0")
      #ord(d['state'])  #  by node state
      )

  reverse: False
```

**Comment by mightybigcar** [comment]
That one doesn't work - I get the same KeyError as previously.

I've logged into gitter.

**Comment by sfranky** [comment]
Issue solved! Culprit was the absence of some additional states (as stated by fotis)
```
Rs: suspended_of_user
Rq: queued_of_user
Rt: transferring_of_user
Rr: running_of_user
```
**Will be fixed in next commit!**
A slight change in the existing sorting in qtopconf.yaml is also required.
under sorting/user_sort subkey:
```
      int(re.sub(r'[A-Za-z _.-]+', '', d['domainname']))
```
has to be changed into
```
      int(re.sub(r'[A-Za-z _.-]+', '', d['domainname']) or "0")
```

**Comment by fgeorgatos** [comment]
I think it's good to report explicitly that the current develop branch has
needed fixes in.

On 27 February 2016 at 01:05, Sotiris Fragkiskos <notifications@github.com>
wrote:

> Issue solved! Culprit was the absence of some additional states (as stated
> by fotis)
>
> Rs: suspended_of_user
> Rq: queued_of_user
> Rt: transferring_of_user
> Rr: running_of_user
>
> *Will be fixed in next commit!*
> A slight change in the existing sorting in qtopconf.yaml is also required.
> under sorting/user_sort subkey:
>
>       int(re.sub(r'[A-Za-z _.-]+', '', d['domainname']))
>
> has to be changed into
>
>       int(re.sub(r'[A-Za-z _.-]+', '', d['domainname']) or "0")
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/qtop/qtop/issues/158#issuecomment-189544082>.
>



-- 


echo "sysadmin know better bash than english"|sed s/min/mins/ \
  | sed 's/better bash/bash better/' # signal detected in a CERN forum
