### ISSUE TITLE
When I do git clone and run it with no cmdline switches, it fails...

### ISSUE THREAD

**Issue by lookfwd** [qtop/qtop#164]
Here's the error message:

```
$ ./qtop.py 
CRITICAL - No suitable scheduler was found. Please define one in a switch or env variable or in qtopconf.yaml.
For more help, try ./qtop.py --help
Log file created in /Users/lookfwd/.local/qtop/logs/qtop.log
ERROR - Uncaught exception
Traceback (most recent call last):
  File "./qtop.py", line 1783, in <module>
    config['schedulers'],
  File "./qtop.py", line 1200, in decide_batch_system
    scheduler = auto_get_avail_batch_system()
  File "./qtop.py", line 973, in auto_get_avail_batch_system
    raise NoSchedulerFound
```

... you guys get my point I guess! ;)

**Comment by sfranky** [comment]
But why would you expect it to run without any arguments? Do you expect cp to run without arguments? :P 
An informative message is printed, and a pointer to more help. What would you expect to see? 
What would @fgeorgatos expect to see?

**Comment by sfranky** [comment]
hm maybe help by default?

**Comment by fgeorgatos** [comment]
so far, it is how it was designed to be :) if you feel it should be otherwise, shoot how

**Comment by lookfwd** [comment]
`Welcome my friend! Here's an exception for you! Have a nice day!`

help or demo would be much nicer behaviour for what will likely be someone's first interaction with the system :)

**Comment by sfranky** [comment]
error handled in next release, 0.8.9, out soon!
