### ISSUE TITLE
Anonymisation feature temporarily unavailable until completely implemented

### ISSUE THREAD

**Issue by sfranky** [qtop/qtop#170]
Due to the input files not being anonymised yet, this feature will be out of service for a while ;)

**Comment by fgeorgatos** [comment]
let's have it in ``--experimental`` mode instead?!

**Comment by fgeorgatos** [comment]
handled for now by adding `--experimental` flag, in PR #276 
(it will always be called experimental, since it can't be anything else, as a matter of user/site safety)
