### ISSUE TITLE
support for core ranges mapping to job in pbs systems

### ISSUE THREAD

**Issue by sfranky** [qtop/qtop#172]
instead of core/job assignments, core-range/job assignments should be also parseable, e.g. 2, 5-10/235235.blah.blah

**Comment by sfranky** [comment]
possible fix in related branch (commit 573dc25c830b54a1b60a811c46b05e70bffb811c)

**Comment by fgeorgatos** [comment]
it would be nice to have a PR for review(s)!

**Comment by sfranky** [comment]
PR https://github.com/qtop/qtop/pull/177

**Comment by sfranky** [comment]
fixed
