### ISSUE TITLE
when you run `qtop.py -w 1` and press ctrl-c, you get uncaught exception

### ISSUE THREAD

**Issue by fgeorgatos** [qtop/qtop#173]
reported by ananke on freenode

**Comment by sfranky** [comment]
been working on that, will probably be included in a next release

**Comment by fgeorgatos** [comment]
IMHO, this is not too big deal, just annoyance that the stacktrace changes each time (not big surprise!). 
Just a little bit exception handling could be a good idea. Interestingly, this could combine very well with #174, because you could implement the try-except clause in the first invocation file instance!

**Comment by sfranky** [comment]
fixed in #255

**Comment by fgeorgatos** [comment]
working with thanks!
