### ISSUE TITLE
can't see what the required version of python is - there should be an automated check

### ISSUE THREAD

**Issue by fgeorgatos** [qtop/qtop#174]
reported by `joshd` on freenode

**Comment by sfranky** [comment]
if python used is unsupported, a msg is printed:
```
        logging.critical("Only python versions 2.6.x and 2.7.x are supported. Exiting")
```
(Is it not?)

**Comment by jodavies** [comment]
With python 2.4.3, I get
```
$ ./qtop.py 
  File "./qtop.py", line 47
    yield
        ^
SyntaxError: invalid syntax
```

**Comment by sfranky** [comment]
I think this has to do with the fact that python 2.4 does not yet have context managers (this whole thing is wrapped in a with statement). What I don't get is how execution reachs this point, there's explicit  checking for python version in line 1761 (in the master branch). Have you messed with the code? could you do a fresh clone and retry?

**Comment by jodavies** [comment]
That is with a fresh clone, yes

**Comment by sfranky** [comment]
I was able to reproduce it. I have to say, this is the strangest thing I've encountered in python so far. It looks like it starts executing functions before main even starts!! normal debugging doesn't work either.. Will look into it further at some point.

**Comment by fgeorgatos** [comment]
here's an answer; 

unsurprisingly, it involves a certain kind of factorization, so that check is invoked at right time:
http://stackoverflow.com/questions/446052/how-can-i-check-for-python-version-in-a-program-that-uses-new-language-features

**Comment by fgeorgatos** [comment]
btw. I realize that in this issue we never stated that explicitly: 
* python involves a compilation step before execution; that implies the above behavior...

**Comment by sfranky** [comment]
The only thing that seems to be working out of this SO link is this:
```import sys; if sys.version_info > ( 2, 4, 0, None, None ): execfile('the real script')``` 
which requires wrapping qtop.py in another file containing just the snipped above. 
Frankly, I'd like to avoid doing that !!

**Comment by fgeorgatos** [comment]
i'm afraid your last proposed technique is the only way to handle this safely ( if we want to do that)

**Comment by sfranky** [comment]
What you are referring to was not *proposed*, I was only protesting against the madness of the idea ;)
For me, the following should suffice to scare off python 2.4 users:
![image](https://cloud.githubusercontent.com/assets/1530259/20443376/40e361be-add5-11e6-82e3-8769b8b05a57.png)
I'll be closing this, if there are no further objections.

**Comment by sfranky** [comment]
As demonstrated, it's impossible to handle without resorting to "wrapping qtop.py in another file", so I'll be closing this..

**Comment by fgeorgatos** [comment]
this could be handled at least minimally under `setup.py`, like this:
http://stackoverflow.com/questions/19534896/enforcing-python-version-in-setup-py
I'm reopening the issue, since the minimum resolution to this is very trivial AND does not affect `qtop.py`!

**Comment by fgeorgatos** [comment]
fi.
```
from setuptools import setup

import sys
if sys.version_info < (2,5):
    sys.exit('Sorry, Python < 2.5 is not supported')

with open("README.md", 'r') as f:
    long_description = f.read()

setup(
   name='qtop',
   version='0.9',
   description="""qtop: the fast text mode way to monitor your cluster's utilization and status; 
      the time has come to take back control of your cluster's scheduling business""",
   license="MIT",
   long_description=long_description,
   author='Sotiris Fragkiskos',
   author_email='sfranky@gmail.com',
   url="https://github.com/qtop/qtop",
   packages=['qtop'],
   ## install_requires=['bar', 'foo'], #external packages as dependencies
   scripts=[
            'qtop',
            ##'scripts/helloworld',
           ]
)
```

btw. setting up `setup.py` involves a registration step which is described over here:
http://stackoverflow.com/questions/1471994/what-is-setup-py?rq=1

**Comment by fgeorgatos** [comment]
There is a check now via `if sys.version_info < (2, 5):` under `setup.py`, so we consider this resolved:
https://github.com/qtop/qtop/pull/228/files#diff-2eeaed663bd0d25b7e608891384b7298
ie. #228 provides for this!
