### ISSUE TITLE
uncaught exception when trying to run qtop:

### ISSUE THREAD

**Issue by dominikborkowski** [qtop/qtop#176]
This is on a Torque/Moab, running on SLES11 SP3:

dom@sfxlogin1:~/Universe/qtop> ./qtop.py
ERROR - Uncaught exception
Traceback (most recent call last):
  File "./qtop.py", line 1796, in <module>
    worker_nodes = get_qnames_per_worker_node(worker_nodes)
  File "./qtop.py", line 1724, in get_qnames_per_worker_node
    worker_node.setdefault('qname', set()).update((queue_of_job_id[job_id][0] for job_id in _job_ids))
  File "./qtop.py", line 1724, in <genexpr>
    worker_node.setdefault('qname', set()).update((queue_of_job_id[job_id][0] for job_id in _job_ids))
KeyError: '2024664'

dom@sfxlogin1:~/Universe/qtop> python --version
Python 2.6.9

I can provide raw output of qstat if it would be helpful.

Cheers!

**Comment by sfranky** [comment]
if you could provide qstat, qstat_q, pbsnodes -a output, it would be perfect! If not, 2-3 respective entries of each file would do.

**Comment by dominikborkowski** [comment]
Full output at:
https://gist.github.com/dominikborkowski/32b12c35c57152874c2e

I also assume you were asking for 'qstat -q' rather than 'qstat_q'

Thanks!

**Comment by sfranky** [comment]
Could you check if branch https://github.com/qtop/qtop/tree/bugfix-pbs-regex fixed the problem?
It seems to run on mine now! does job state "H" stand for halted?

**Comment by dominikborkowski** [comment]
It works now, thanks!

'H' stands for Hold, here are some details regarding that state for maui/moab:

http://docs.adaptivecomputing.com/mwm/archive/6-0/11.1jobholds.php

**Comment by sfranky** [comment]
ok i'll change the name in the settings. Thanks for the info I'll have a look!

**Comment by sfranky** [comment]
merged into develop. Closing issue

**Comment by fgeorgatos** [comment]
btw. good catch! no idea how the `Hold` state escaped us for so long
(it may be because I'm doing *GE on daily basis since long time now :-p )
