### ISSUE TITLE
"i want to like qtop, but damn, the way it redraws its screen is so annoying..."

### ISSUE THREAD

**Issue by fgeorgatos** [qtop/qtop#179]
by ananke on Freenode

FG: indeed, it would be probably better to precalculate all the output (ie. >$TMPFILE)
and then use `cat` to push that out in one go. There is another related issue about it,
it certainly contributes to the half-cooked output I see to some hung terminals of mine 
(not caused by qtop, but certainly an effect)

**Comment by sfranky** [comment]
Should be fixed in feature-branch https://github.com/qtop/qtop/tree/ft-enhance-display-speed

**Comment by fgeorgatos** [comment]
you may love qtop again, this should be called fixed, by now!

**Comment by fgeorgatos** [comment]
via #180

**Comment by fgeorgatos** [comment]
@dominikborkowski: should be OK by now, let us know how much your like this!
