### ISSUE TITLE
Errors out with PBS Array Files

### ISSUE THREAD

**Issue by negregg** [qtop/qtop#199]
qtop.py appears not to be able to handle qstat output that contains array jobs.  

Below is the error that I recieve.  Thanks for the help.

 ./qtop.py      
Line: 513876[].srih0001          ...RANS.MDET4000 user             0 R group not properly parsed by regex expression.
Traceback (most recent call last):
  File "./qtop.py", line 2034, in <module>
    job_ids, user_names, job_states, job_queues = scheduling_system.get_jobs_info()
  File "/tmp/qtop/qtop/plugins/pbs.py", line 182, in get_jobs_info
    qstats = self.qstat_maker.extract_qstat(self.qstat_file)
  File "/tmp/qtop/qtop/plugins/pbs.py", line 60, in extract_qstat
    qstat_values = self._process_qstat_line(re_search, line, re_match_positions)
  File "/tmp/qtop/qtop/serialiser.py", line 26, in _process_qstat_line
    job_id, user, job_state, queue = [m.group(x) for x in re_match_positions]
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by sfranky** [comment]
could you please provide the tar file produced by running qtop as usual, but adding -LL at the end ? if you have sensitive data that you don't want to expose, then maybe a couple of lines from qstat, qstat -q and pbsnodes ?

**Comment by fgeorgatos** [comment]
@negregg: 
also, I'm not sure if you can still extract something useful by using the experimental anonymization feature. It has been almost working in the past, but we eventually found out that the function was not exactly complete (so I'm not even sure if I should be doing that code reference at all...)

**Comment by negregg** [comment]
Thanks @sfranky @fgeorgatos for the assist.  I tried the -LL command as well but it is erroring out as well.  Error output for the -LL command is below.  I have manually provided the qstat and pbsnodes output as requested.  

Also note, to get all the information you might need for output you might need to use the "-t" flag with qstat to see the individual array jobs.  

Please let me know if you need anything else.

-LL Error output:
mountaineer:/opt/admin/qtop/qtop# ./qtop -LL
ksh: ./qtop: not found [No such file or directory]
mountaineer:/opt/admin/qtop/qtop# ./qtop.py -LL
Traceback (most recent call last):
  File "./qtop.py", line 2028, in <module>
    fileutils.init_sample_file(options, config, SAMPLE_FILENAME, scheduler_output_filenames, QTOPCONF_YAML, QTOPPATH)
  File "/opt/admin/qtop/qtop/fileutils.py", line 67, in init_sample_file
    for fn in scheduler_output_filenames if os.path.isfile(scheduler_output_filenames[fn])]
  File "/opt/admin/qtop/qtop/fileutils.py", line 80, in add_to_sample
    sample_out = sample_method.open(os.path.join(savepath, sample_file), mode='a')
  File "/usr/lib64/python2.6/tarfile.py", line 1687, in open
    return cls.taropen(name, mode, fileobj, **kwargs)
  File "/usr/lib64/python2.6/tarfile.py", line 1697, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/usr/lib64/python2.6/tarfile.py", line 1577, in __init__
    if self.next() is None:
  File "/usr/lib64/python2.6/tarfile.py", line 2328, in next
    raise ReadError(str(e))
tarfile.ReadError: empty header



[qtop_output.zip](https://github.com/qtop/qtop/files/277454/qtop_output.zip)

**Comment by fgeorgatos** [comment]
thank you @negregg ; 

in the meantime, as we fix it, you might be luckier with the old qtop variant, written in bash:
 * http://cern.ch/fotis/QTOP/
it has its own issues but it was handling array jobs from time to time!

**Comment by sfranky** [comment]
@negregg could you please try this branch https://github.com/qtop/qtop/tree/ft-array-jobs and tell me if it works as expected?

**Comment by negregg** [comment]
@sfranky Thanks!  That got it and it is working as expected.

**Comment by fgeorgatos** [comment]
nice to know! thank you for reporting back. I'd close this issue as soon as the PR gets merged in!

btw.
Running `qtop -w` is very effective to catch bugs on either the system or the tool, so highly suggested!

F.

**Comment by fgeorgatos** [comment]
this has been fixed some time ago and now merged, therefor closing...
