### ISSUE TITLE
strict checking

### ISSUE THREAD

**Issue by sfranky** [qtop/qtop#20]
add a --strict-checking switch that cross-checks between all input files for consistency of jobs (are counted R+Q jobs in Accounting Summary exactly as many as displayed in the Worker Nodes Occupancy table?)

**Comment by fgeorgatos** [comment]
bump priority

**Comment by sfranky** [comment]
if the input files which qtop reads have conflicting information a warning message should be spitted out
(esp. mismatch on number of jobs)
