### ISSUE TITLE
Consider trimming down common node prefix, when in transposed mode

### ISSUE THREAD

**Issue by fgeorgatos** [qtop/qtop#201]
fi. all nodes of a cluster might start with `nl-amsix-tulip-...`;
no need to consume so much screen real estate, when it is possible to "collapse" the information?

**Comment by sfranky** [comment]
Desperately need to write the rest of the documentation at some point...
This already exists as a feature: Remapping key in the configuration file, somewhere around line 140.
You could write something like
``` - nl-amsix-tulip-(\w+): tu_\1``` 
An automation of this would be unnecessarily risky.

**Comment by fgeorgatos** [comment]
ok, probably this is reasonable (at least, there is an immediate way to handle it)
