### ISSUE TITLE
oh, too many /tmp/tmp* files, let's prevent this

### ISSUE THREAD

**Issue by fgeorgatos** [qtop/qtop#204]
Lots of files of this type, likely coming from the watch feature (since their creation rate is related):

```
$ head -2 /tmp/tmp1RYhv7.out
./qtop.py ## Queueing System report tool. All bugs added by sfranky@gmail.com. Cross fingers now...
```

**Comment by fgeorgatos** [comment]
actually, THIS! it has become a pain, because far too many /tmp files get created, at top level.
After a while, this clutters /tmp directory a lot

**Comment by sfranky** [comment]
fix [in PR](https://github.com/qtop/qtop/pull/215)

**Comment by sfranky** [comment]
err final fix in [PR 223](https://github.com/qtop/qtop/pull/223)
