### ISSUE TITLE
oops, this should not bail out: watch -d './qtop/qtop.py -Fg|cat'

### ISSUE THREAD

**Issue by fgeorgatos** [qtop/qtop#206]
confirmed as of 92d7a3d, it seems to throw:

```
$ watch -d './qtop/qtop.py -Fg|cat'
Traceback (most recent call last):
   File "./qtop/qtop.py", line 1987, in <module>
old_attrs = termios.tcgetattr(0)
termios.error: (25, 'Inappropriate ioctl for device')
```

**Comment by fgeorgatos** [comment]
OK, I googled this issue and it seems to be in this class:
http://stackoverflow.com/questions/31862983/pexpect-and-pycharm-inappropriate-ioctl-for-device

it was on centos6.8; if you can't reproduce it, it seems I should be giving you access to my R-Pi instead! :
https://www.raspberrypi.org/forums/viewtopic.php?f=32&t=132111

**Comment by fgeorgatos** [comment]
also, these 2 are telling:
https://github.com/andresriancho/w3af/issues/552
https://github.com/magmax/python-readchar/issues/11
which gives a pointer to:
https://github.com/pexpect/ptyprocess 
v-e-r-y interesting (see the README)

**Comment by fgeorgatos** [comment]
this bug starts to become very painful; I *need* to put this whole thing under watch and it doesn't help:
`/qtop.py -Fg -1 -3|grep d;pdsh -a uname -r 2>/dev/null|dshbak -c;ssh myhost w`

**Comment by fgeorgatos** [comment]
1 last man standing, looking good here:

```
[root@ussf-prd-brhn01 ~]# /home/fgeorgatos/qtop/qtop.py -Fg -1 -3|grep d;pdsh -a uname -r 2>/dev/null|dshbak -c;ssh ussf-msk-brln01 w
[...]
 ===> Worker Nodes occupancy <=== (wnid_lines/core_map/Node state/queue name)
gen128-017|5_______________________________________|d |s|
Log file created in /root/.local/qtop/logs/qtop.log
----------------
gen128-[001-016,018-024],msk128-[001-003],msk256-[001-008,010-020],rgh128-[001-004],ussf-msk-brln01,ussf-prd-brhn[01-02],ussf-prd-brln[01-02]
----------------
2.6.32-642.6.2.el6.x86_64
----------------
gen128-017
----------------
2.6.32-642.3.1.el6.x86_64
 04:03:08 up 8 min,  0 users,  load average: 0.01, 0.18, 0.13
USER     TTY      FROM              LOGIN@   IDLE   JCPU   PCPU WHAT
[root@ussf-prd-brhn01 ~]# date
Fri Nov 25 04:03:26 PST 2016
```

**Comment by fgeorgatos** [comment]
Alright, we have a workaround here:
```
    try:
        old_attrs = termios.tcgetattr(0)
    except termios.error:
        old_attrs = ''
```

To be sure, that still requires `2>/dev/null` or, you get the complaints about 'Inappropriate ioctl for device';
a far better approach would be, to check about `/dev/tty` in the beginning and if it fails simply skip the loop.

**Comment by sfranky** [comment]
fix in https://github.com/qtop/qtop/pull/256

**Comment by fgeorgatos** [comment]
handled via #256 which means: DONE! closing
