### ISSUE TITLE
Feature request: ability to record intermediate inputs/outputs, for future playback

### ISSUE THREAD

**Issue by fgeorgatos** [qtop/qtop#208]

**Comment by fgeorgatos** [comment]
JSON already does that - documentation how to extract it?!

**Comment by sfranky** [comment]
what do you mean? json output is saved in /tmp/qtop_results_<USER>, along with the .out file

**Comment by fgeorgatos** [comment]
@sfranky : can we document how to extract that (and only that) in a way that allows replay?
(if we have already done that, I've missed it!)

**Comment by sfranky** [comment]
the information *is extracted*, the question is how to play back .out files consecutively. Maybe a bash script with a while loop  over the last N. out files? clear;cat outfile etc.  care to lend a hand?

**Comment by fgeorgatos** [comment]
@sfranky: you have freedom of implementation here, since this feature did not exist before.
The ability to `--replay` past observations over several seconds/minutes would be a golden feature.

**Comment by fgeorgatos** [comment]
fixed via #225 ; it would be nice to assume a default start time ("fail as little as possible" principle!). np.

**Comment by sfranky** [comment]
fail as little as possible to read the --help, would be nice, too :)
