### ISSUE TITLE
Issues with PBS Pro and job arrays

### ISSUE THREAD

**Issue by stetner** [qtop/qtop#219]
I have pulled down the latest version off the develop branch and have noticed some issues with job arrays.

1)
```
$ ./qtop.py
Line: 94646[].delta     hap_GQ_0028.0A   c.simons                 0 B cas not properly parsed by regex expression.
Traceback (most recent call last):
  File "./qtop.py", line 2068, in <module>
    job_ids, user_names, job_states, job_queues = scheduling_system.get_jobs_info()
  File "/shares/common/users/d.stetner/build/qtop-develop/plugins/pbs.py", line 182, in get_jobs_info
    qstats = self.qstat_maker.extract_qstat(self.qstat_file)
  File "/shares/common/users/d.stetner/build/qtop-develop/plugins/pbs.py", line 60, in extract_qstat
    qstat_values = self._process_qstat_line(re_search, line, re_match_positions)
  File "/shares/common/users/d.stetner/build/qtop-develop/serialiser.py", line 26, in _process_qstat_line
    job_id, user, job_state, queue = [m.group(x) for x in re_match_positions]
AttributeError: 'NoneType' object has no attribute 'group'
```
This is solved by adding all the possible states in plugins/pbs.py

```
$ diff plugins/pbs.py plugins/pbs.py.dgs
19c19
<                              r'(?P<state>[CWRQEH])\s+' \
---
>                              r'(?P<state>[BCEFHMQRSTUWX])\s+' \
```
2)  Then this error appears
```
$ ./qtop.py
Traceback (most recent call last):
  File "./qtop.py", line 2070, in <module>
    worker_nodes = scheduling_system.get_worker_nodes()
  File "/shares/common/users/d.stetner/build/qtop-develop/plugins/pbs.py", line 169, in get_worker_nodes
    pbs_values['core_job_map'] = dict((core, job) for job, core in self._get_jobs_cores(jobs))
  File "/shares/common/users/d.stetner/build/qtop-develop/plugins/pbs.py", line 169, in <genexpr>
    pbs_values['core_job_map'] = dict((core, job) for job, core in self._get_jobs_cores(jobs))
  File "/shares/common/users/d.stetner/build/qtop-develop/plugins/pbs.py", line 227, in _get_jobs_cores
    core, job = core_job.strip().split('/')
ValueError: too many values to unpack
```

[qtop_sample_d.stetner.tar.zip](https://github.com/qtop/qtop/files/591132/qtop_sample_d.stetner.tar.zip)

**Comment by sfranky** [comment]
@stetner thanks for the feedback and for providing the solution to 1!
Regarding 2, are you sure that the previous version of qtop you used worked with the exact same input? The job-core format is a bit different than what is expected.

**Comment by sfranky** [comment]
@stetner could you please provide what the extra state abbreviations BFHMQRWX stand for? so i can insert them into the qtopconf.yaml file.
Otherwise, qtop will be supporting job-ids in the format XXXXXX[X] very very soon (it just disregards the brackets, shouldn't make any difference, as I understand it)

**Comment by fgeorgatos** [comment]
resolved via #220  (or reopen this if not)

**Comment by stetner** [comment]
Hi Sotiris,


This is from the 13.1 PBS Pro doco:



pbs.JOB_STATE_BEGUN      B    Job arrays only: job array has started



pbs.JOB_STATE_EXITING    E    Job is exiting after having run



pbs.JOB_STATE_EXPIRED    X    Subjobs only; subjob is finished (expired.)



pbs.JOB_STATE_FINISHED    F   Job is finished: job executed successfully, job was terminated while running, job execution failed, or job was deleted before execution



pbs.JOB_STATE_HELD    H    Job is held.



pbs.JOB_STATE_MOVED    M    Job has been moved to another server



pbs.JOB_STATE_QUEUED    Q    Job is queued, eligible to run or be routed



pbs.JOB_STATE_RUNNING    R    Job is running



pbs.JOB_STATE_SUSPEND    S    Job is suspended by PBS so that a higher-pri- ority job can run.



pbs.JOB_STATE_SUSPEND_ USERACTIVE    U    Job is suspended due to workstation becom- ing busy



pbs.JOB_STATE_TRANSIT    T    Job is in transition (being moved to a new location)



pbs.JOB_STATE_WAITING    W    Job is waiting for its requested execution time to be reached, or the job’s specified stagein request has failed for some reason.





On Nov 16, 2016, at 01:51 AM, Sotiris Fragkiskos <notifications@github.com> wrote:



@stetner could you please provide what the extra state abbreviations BFHMQRWX stand for? so i can insert them into the qtopconf.yaml file.
Otherwise, qtop will be supporting job-ids in the format XXXXXX[X] very very soon (it just disregards the brackets, shouldn't make any difference, as I understand it)

**Comment by stetner** [comment]
Hi Sotiris,



I had make some hacks in the old version to get it to work but never got around to entering a report, sorry :(



Doug


On Nov 15, 2016, at 06:57 PM, Sotiris Fragkiskos <notifications@github.com> wrote:



@stetner thanks for the feedback and for providing the solution to 1!
Regarding 2, are you sure that the previous version of qtop you used worked with the exact same input? The job-core format is a bit different than what is expected.

**Comment by stetner** [comment]
I have pulled down the latest develop and it seems to be working fine:

 fgeorgatos committed on GitHub Merge pull request #221 from qtop/fix-func-tests-reset 

Thanks!

**Comment by sfranky** [comment]
thanks very much for this!
I ll be adding the info soon.
