### ISSUE TITLE
High CPU usage by qtop

### ISSUE THREAD

**Issue by ravikishorek** [qtop/qtop#242]
I have observed that the qtop from the development branch is spiking at almost 45% of a core usage at times. Upon looking at the log file, I find the following segments of text repeatedly. Do you have any idea on what could be happening?

Command issued: ['cat', '-E', '/home/ravikk/.local/qtop/getent_passwd.txt']
WARNING - You have to set a proper command to get the passwd file in your qtopconf.yaml file.
WARNING - Error returned by getent: cat: /home/ravikk/.local/qtop/getent_passwd.txt: No such file or directory

**Comment by sfranky** [comment]
It does spike at times, it has to download the data from the cluster and process it every x seconds, essentially it reruns every x seconds.

What you're seeing as a warning is unrelated, it has to do with the fact that you don't have that file mentioned. If you did, you'd have that last empty column filled with user info.

**Comment by fgeorgatos** [comment]
OK, I think there is a smart way out of this, create a file under `/dev/shm` which resembles `/etc/passwd` - it doesn't need to have more than a line or perhaps even zero.

That would untangle invocations to -possibly- parallel filesystem code under `/home`.

ie. try to modify `qtopconf.yaml` to point to that file (or perhaps even to `/dev/null`, it might work).

let us know how it goes!

**Comment by ravikishorek** [comment]
Hi sfranky, fgeorgatos,

I have been using qtop for a while on our cluster and it was pretty much bounded by a constant 4 - 5% of CPU usage with no spike. Some changes possibly introduced recently have led to some users getting a CPU usage spike of 45 - 50%, while some users are still bounded by 5%, which is very strange. To do some regression, I went back into the commits in the master branch and reverted to commit 88ad38abc8ccbd2deadca4c7443ea07c09147074 , where I again found that the usage was consistently bound by 5% for all users. So, it is definitely a change that has come from one of the recent commits. Do you have any idea why this could be happening?

**Comment by ravikishorek** [comment]
@fgeorgatos , the trick to point to /dev/null is working, and we see no messages being written to the log now. thank you

**Comment by sfranky** [comment]
@ravikishorek Wait, do you mean you no longer get the spikes?

**Comment by ravikishorek** [comment]
@sfranky Indeed, I get no spikes and the CPU usage is bounded between 4.5 to 5.4 % of a core when I revert to the commit mentioned before. However, the latest commit on the head node spikes all the way between 10% to 45% for some users

**Comment by sfranky** [comment]
@ravikishorek I meant, did you mean you no longer get the spikes because of /dev/null  :) Because that doesn't make sense to me, when combined with the different commits comment

**Comment by ravikishorek** [comment]
@sfranky Sorry for the confusion. The /dev/null doesn't have anything to do with the CPU usage spike. It just prevents writing to the log file (which bloats over time). The CPU usage is linked only with the different commits, with the older commit consistently working at 5% CPU usage and the latest commit spiking between 10 - 45% of a Core.

**Comment by sfranky** [comment]
@ravikishorek ok this looks serious, I will look into it! thanks for the feedback

**Comment by fgeorgatos** [comment]
hi @ravikishorek

is this still reproducible, in either master or develop branch?
If not, please close the issue, if you agree that no further effort is needed in this!

**Comment by ravikishorek** [comment]
I have tested using the new master branch, and I can confirm that the CPU usage is capped at 4.5%, which is fantastic! Thank you for fixing the issue.
