### ISSUE TITLE
PBS plugin fails when jobs use non-consecutive CPUs

### ISSUE THREAD

**Issue by eddedmondson** [qtop/qtop#265]
The pbsnodes command on my system (Torque 5.1.0) can produce output like this in its jobs fields:
`27/1282133.node-00,28/1282134.node-00,31/1282135.node-00,15,21-22,24/1282033.node-00,2,6,8-9/1282034.node-00,10,12,14,20/1282038.node-00`
This causes the PBS plugin to fail as the jobs are split on commas before being passed to _get_jobs_cores?

**Comment by fgeorgatos** [comment]
hm.. this is a new more compact representation. interesting, thanks for the issue, tbd!

**Comment by sfranky** [comment]
@eddedmondson 
They were indeed split on commas, but not on any comma. Your case was a bit more advanced, though.
Could you please try the proposed fix in PR https://github.com/qtop/qtop/pull/266 ?

**Comment by eddedmondson** [comment]
Hi, yes that looks like it works! Thanks!
