### ISSUE TITLE
Option to remove empty core lines doesn't work

### ISSUE THREAD

**Issue by sbutcher** [qtop/qtop#267]
Hello
Running 

` qtop -b sge -FGwrT`

doesn't remove empty core lines on Centos6 and Centos7 machines i've tested on. see attached image for example.

![selection_291](https://cloud.githubusercontent.com/assets/4619907/21045347/e767ae78-bdf7-11e6-855e-a8b9d82f17de.png)

**Comment by sfranky** [comment]
Hi, sorry, there is a lack of documentation here. Empty core lines refer to lines that are *entirely* filled with #s, in essence cores that do not really exist for the displayed machines. In the screenshot, you also have unused cores (on the left and right hand side of the screen), so it wouldn't make sense to just remove them, it would draw an unreliable image of the cluster. You can always transpose the matrix (and maybe your monitor, if possible!!) ;)

**Comment by sbutcher** [comment]
ah, thanks for clarification, not a bug then.

**Comment by sfranky** [comment]
@sbutcher 
stay tuned, I'm adding a double -rr to also remove ____####___________ this kind of lines. That real estate is valuable!!

**Comment by sfranky** [comment]
@sbutcher if you want to try it out,, check PR https://github.com/qtop/qtop/pull/271
It does what you expected, plus you should be able to toggle between those states, showing all cores, hiding corelines full of `'#'`s and hiding corelines with `'#'`s and `'_'`s.

**Comment by sfranky** [comment]
fixed in latest develop branch

**Comment by sbutcher** [comment]
works for me , thanks guys!
