### ISSUE TITLE
get_jobs_cores fails

### ISSUE THREAD

**Issue by stetner** [qtop/qtop#293]
This fails to show cores on my PBSpro system unless the 1st is used and the second commented out:

                jobs = re.split(r'(?<=[A-Za-z0-9]),\s?', block['jobs'])
                # jobs = re.findall(r'[0-9][0-9,-]*/[^,]+', block['jobs'])

Line 170 in qtop_py/plugins/pbs.py

```
$ qtop -V
qtop current version: 0.9.20161222
```

**Comment by sfranky** [comment]
could you please send me your input files, so that I can check the reason for this?

**Comment by stetner** [comment]
Here it the output

[qtop_sample_d.stetner.tar.gz](https://github.com/qtop/qtop/files/1101017/qtop_sample_d.stetner.tar.gz)

**Comment by sfranky** [comment]
should be fixed in the next develop version !

**Comment by sfranky** [comment]
@stetner this is now merged in develop branch, please let us know if you find any problems!

**Comment by stetner** [comment]
Works great!




On Jun 29, 2017, at 06:17 AM, Sotiris Fragkiskos <notifications@github.com> wrote:



@stetner this is now merged in develop branch, please let us know if you find any problems!

**Comment by fgeorgatos** [comment]
closing, since it's resolved several merges ago, let's focus on the other one!
