### ISSUE TITLE
Missing 'Eye' Icon for Password Visibility Toggle

### ISSUE THREAD

**Issue by ayushsingh199** [qtop/qtop#332]
#### Description
The password input field is missing the "eye" icon, which allows users to toggle the visibility of the password while typing. This feature is important for usability, as it helps users confirm their password input without errors.

#### Expected Behavior
There should be an "eye" icon inside the password input field that, when clicked, allows the user to toggle between showing and hiding the password.

#### Actual Behavior
- No "eye" icon is present in the password field, making it difficult for users to see what they are typing.

#### Steps to Reproduce
1. Go to the login or registration page with the password field.
2. Look for an "eye" icon inside the password input field (none exists).
<img width="454" alt="Screenshot 2024-10-15 at 1 12 24 PM" src="https://github.com/user-attachments/assets/2966aabf-2457-43b8-87bb-c113a316e55b">

**Comment by fgeorgatos** [comment]
For clarity: 
- this will occur when following the link cern.ch/fotis/QTOP
- a ticket has been opened for this at CERN, expecting answer to find how to handle it.
- if this is not corrected before end of the week, ask me for the historic tarball qtop.tar.gz , if that is useful to you.

**Comment by ayushsingh199** [comment]
So should i solve the issue or not , please clarify.

**Comment by fgeorgatos** [comment]
yes, I am inclined to resolve it since this is external to this repository. So, closing it now.
