### ISSUE TITLE
if possible, do not rely on intermediate file

### ISSUE THREAD

**Issue by fgeorgatos** [qtop/qtop#45]
In fact, we should not only avoid relying upon an intermediate yaml file (it could be dumped on the fs for debugging, yet left in memory as data structure for usage), we should also get away with:
* `qstat -F -xml -u "*" >/tmp/q && mv /tmp/q qstat.F.xml.stdout`

The above expression is currently necessary, in order to update the information in an atomic manner.

**Comment by sfranky** [comment]
@fgeorgatos  atomicity should be taken care of internally within execute_shell_batch_commands() now
