### ISSUE TITLE
[VIS] add a new node line, or column, displaying queue per each node

### ISSUE THREAD

**Issue by sfranky** [qtop/qtop#59]
An extra line in the wn occupancy should display the initial of the queue the worker node belongs to. If it belongs to more than one queues, display a suitable character (question mark/capitalised letter)

**Comment by sfranky** [comment]
also, nodes belonging in a queue named "whole" (for SGE clusters) should automatically expand to take up all cores of the node.

**Comment by sfranky** [comment]
instead, an option to display more lines is available.

**Comment by fgeorgatos** [comment]
can you make it tunable to show the complete queue name? (esp. in horizontal mode)

**Comment by sfranky** [comment]
settled on having a legend somewhere explaining what queue initial corresponds to which queue

**Comment by sfranky** [comment]
Not yet resolved, will do in a next iteration

**Comment by fgeorgatos** [comment]
relatively well done so far, fixed! I'd consider the legend & full queue name as a separate issue, yet ok!
