### ISSUE TITLE
tarball creation

### ISSUE THREAD

**Issue by sfranky** [qtop/qtop#60]
Input files (fetched by issuing the appropriate queueing commands, qstat, oarstat, etc) and intermediate yaml files should be gathered in a directory and put into a tarball.

**Comment by sfranky** [comment]
directory name should be fixed

**Comment by sfranky** [comment]
-t should include logs, original input files, yaml files and output files
-tt should additionaly include config file, qtop source

**Comment by fgeorgatos** [comment]
bump priority?

**Comment by sfranky** [comment]
almost done, some minor details remaining

**Comment by sfranky** [comment]
FIXED. full data anonymisation pending.
