### ISSUE TITLE
[VIS] Nodes belonging in a queue named "whole" (for SGE clusters) should automatically expand to take up all cores of the node.

### ISSUE THREAD

**Issue by sfranky** [qtop/qtop#68]
Nodes belonging in a queue named "whole" (for SGE clusters) should automatically expand to take up all cores of the node.

**Comment by fgeorgatos** [comment]
this should be a tunable: 
* a list of queues in the config file, should trigger this behavior.

**Comment by fgeorgatos** [comment]
#295 treats this reasonably well, closing
