### ISSUE TITLE
define release process better

### ISSUE THREAD

**Issue by sfranky** [qtop/qtop#81]
https://www.youtube.com/watch?v=xbLVvrb2-fY
~40:00

**Comment by fgeorgatos** [comment]
perhaps:
* git commit # as needed, ensure develop holds all latest commits, including updated README
* git checkout master
* git push # reality check if we are going to stop half-way
* git pull origin develop
* git push # going live
* check for release tag

**Comment by lookfwd** [comment]
Standard release process? e.g. https://github.com/apache/lucene-solr/releases

See also "Release Branches" [here](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow/)

**Comment by sfranky** [comment]
I thought this is pretty much what we're doing, minus the release branch, no?

**Comment by fgeorgatos** [comment]
confirmed: release branches will become of interest post-version 1.0 - still in todo mode...

**Comment by fgeorgatos** [comment]
should we attempt a release sequence with a release branch, on this round?
(not strictly needed up to v1.0, just to kick the tyres at least once before that)

**Comment by fgeorgatos** [comment]
I think we've followed this process before and it works, so I'm resolving this until further notice...

**Comment by fgeorgatos** [comment]
as said: slow but solid, no temptations to delete `develop` via a PR ;-)

**Comment by fgeorgatos** [comment]
OK, here's a little extra how-to rebalance the branches after the release merge:
```
[fgeorgatos@bright-lmod qtop]$ git branch -av
  develop                                 30762ff Merge pull request #194 from qtop/ch-doc-exp
* master                                  22daad6 Merge pull request #196 from qtop/develop
  remotes/origin/HEAD                     -> origin/master
  remotes/origin/bugfix-filters-broken    469e4d6 bugfix: filters broken because of name refactoring
  remotes/origin/bugfix-lxml-not-loaded   fc220c3 lxml check moved into sge module
  remotes/origin/develop                  30762ff Merge pull request #194 from qtop/ch-doc-exp
  remotes/origin/master                   22daad6 Merge pull request #196 from qtop/develop
  remotes/origin/sfranky-patch-1          fd7bccf Update README.md
  remotes/origin/test-add-vagrant-lookfwd 2f6088d fixed version number
[fgeorgatos@bright-lmod qtop]$ git checkout develop
Switched to branch 'develop'
[fgeorgatos@bright-lmod qtop]$ git pull origin master
From https://github.com/qtop/qtop
 * branch            master     -> FETCH_HEAD
Updating 30762ff..22daad6 ### N.B. No merge commit, just fast-forwarding!
Fast-forward
[fgeorgatos@bright-lmod qtop]$ git push
[...]
```

That would then let the two branches have all commits (i.e. also the master merge commit) and restore faith. I presume this sequence can be simplified, i'll check the how later.

**Comment by fgeorgatos** [comment]
Much simplified release process:
(after delivering in develop the right PRs, including updated README & version number)
- git checkout master
- git push # develop should be pushed to origin now
- git merge origin develop
- git push # going live also for master
- appoint a release tag now
