### ISSUE TITLE
queue names display in the matrix should be auto-disabled for non sge systems

### ISSUE THREAD

**Issue by sfranky** [qtop/qtop#99]
The error displayed for now is:
CRITICAL: queue name lines in the matrix are not supported for auto systems

a quick fix for this is to just comment out the relevant lines from the qtopconf.yaml file:
```
 - queue name:  # TODO: this only works for SGE systems
     yaml_key: qname
     label: queue name
     max_len: 2
     systems: [sge]
```

**Comment by fgeorgatos** [comment]
this is fixed?

**Comment by sfranky** [comment]
yes, as the feature is now supported for every system. Also, the "systems" line is in place (before, it lay just there for demo purposes)
